/*
 * This source file was generated by the Gradle 'init' task
 */
package com.osmaldym.jvr;

import com.osmaldym.jvr.screens.Home;

public class App {
    
    public static void main(String[] args) {
        new Home();
    }
}
